### ISSUE TITLE
Scope and tasks

### ISSUE THREAD

**Issue by G-DECARLI** [G-DECARLI/pulseads_project#1]
**Task 1:**

- [ ] Registration of bracelets;
- [ ] Registration of clients;
- [ ] Employee registration;
- [ ] Credit and debit control;
- [ ] Benchmarking of other systems for verification of used fields.
